CREATE TABLE USER (
	USER_ID VARCHAR(20) PRIMARY KEY,
    USR_PW VARCHAR(64) NOT NULL,
    USER_NM VARCHAR(18) NOT NULL,
    USER_AUTH_CD CHAR(2) NOT NULL,
    KEY idx_id(USER_ID),
    KEY idx_nm(USER_NM)
);

COMMIT; -- done

CREATE TABLE NOTICE (
	NOTICE_SEQNO SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOTICE_TITLE VARCHAR(30) NOT NULL,
    NOTICE_CONTENT MEDIUMTEXT NOT NULL,
    NOTICE_VIEW_CNT SMALLINT UNSIGNED NOT NULL,
    NOTICE_LIKE_CNT SMALLINT UNSIGNED NOT NULL,
    NOTICE_REG_DTTM DATETIME NOT NULL,
    NOTICE_REG_USER_ID VARCHAR(20),
    FOREIGN KEY (NOTICE_REG_USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    KEY idx_noti_seqno(NOTICE_SEQNO),
    KEY idx_noti_title(NOTICE_TITLE)
);

COMMIT; -- done


